main: com.herocc.bukkit.core.Core

name: '@Name@'
version: '@Version@'
description: "@Description@"

author: '@Author@'

commands:
  head:
    description: "Summon a Head"
    usage: "/<command> [player] [target]"
    aliases: skull
  fly:
    description: "Fly, regardless of GameMode"
    usage: "/<command> [player] [speed]"
  freeze:
    description: "Prevent a player from moving until they are unfrozen"
    usage: "/<command> <player>"
    aliases: unfreeze
  core:
    desctiption: "Information about Core"
    usage: "/<command>"
  sudo:
    description: "Chat and use commands as other players"
    usage: "/<command> <player> <input>"


permissions:
  core.*:
    description: "Gives access to all of Core's functions and commands"
    default: op
    children:
      core.head: true
      core.fly: true
      core.freeze: true
      core.sudo: true
  core.head:
    description: "Allows you to summon and give player heads"
    children:
      core.head.give: true
      core.head.get: true
  core.head.get:
    description: "Allows you to summon your own heads"
  core.head.give:
    description: "Allows you to give other players someones heads"
  core.fly:
    description: "Allows you to set others and yourself to fly"
    children:
      core.fly.self: true
      core.fly.others: true
  core.fly.self:
    description: "Allows you to toggle your own flight mode"
  core.fly.others:
    description: "Allows you to toggle other people's flight mode"
  core.freeze:
    description: "Allows you to freeze and unfreeze other players"
  core.sudo:
    description: "Allows you to execute commands as other players"
