name: HeroiCraft-Core
version: '@Version@'
main: com.herocc.bukkit.core.Core
description: "@Description@"
authors: [HeroCC]

commands:
  head:
    description: "Summon a Head"
    usage: "/<command> [player] [target]"
    aliases: skull
  fly:
    description: "Fly, regardless of GameMode"
    usage: "/<command> [player] [speed]"
  freeze:
    description: "Prevent a player from moving until they are unfrozen"
    usage: "/<command> <player>"
    aliases: unfreeze
  core:
    desctiption: "Information about Core"
    usage: "/<command>"
  sudo:
    description: "Chat and use commands as other players"
    usage: "/<command> <player> <input>"
  speed:
    description: "Change the speed of flight or walking"
    usage: "/<command> [speed] [player]"
  cmd:
    description: "Get info about a command"
    usage: "/<command> <target>"
    aliases: cmdinfo
  fake:
    description: "Make the block you are pointing at another block just for you"
    usage: "/<command> <blocktype> [<x> <y> <z>]"
    aliases: fakeblock, fb


permissions:
  core.*:
    description: "Gives access to all of Core's functions and commands"
    default: op
    children:
      core.head: true
      core.fly: true
      core.freeze: true
      core.sudo: true
      core.speed: true
      core.cmd: true
      core.fake: true
  core.head:
    description: "Allows you to summon and give player heads"
    children:
      core.head.give: true
      core.head.get: true
  core.head.get:
    description: "Allows you to summon your own heads"
  core.head.give:
    description: "Allows you to give other players someones heads"
  core.fly:
    description: "Allows you to set others and yourself to fly"
    children:
      core.fly.self: true
      core.fly.others: true
  core.fly.self:
    description: "Allows you to toggle your own flight mode"
  core.fly.others:
    description: "Allows you to toggle other people's flight mode"
  core.freeze:
    description: "Allows you to freeze and unfreeze other players"
  core.sudo:
    description: "Allows you to execute commands as other players"
  core.speed:
    description: "Allows you to change your and others fly and walk speed"
    children:
      core.speed.self: true
      core.speed.others: true
  core.speed.self:
    description: "Allows you to change your fly and walk speed"
    children:
      core.speed.self.fly: true
      core.speed.self.walk: true
  core.speed.others:
    description: "Allows you to change other's fly and walk speeds"
    children:
      core.speed.others.fly: true
      core.speed.others.walk: true
  core.speed.self.fly:
    description: "Allows you to change your fly speed"
  core.speed.self.walk:
    description: "Allows you to change your walk speed"
  core.speed.others.fly:
    description: "Allows you to change someone else's fly speed"
  core.speed.others.walk:
    description: "Allows you to change someone else's walk speed"
  core.cmd:
    description: "Allows you to view info about a command"
  core.fake:
    description: "Allows you to set a block to another kind of block temporarily"
